# This is a basic workflow to help you get started with Actions

name: deploy-ml-bundle

# Controls when the workflow will run
on:

  workflow_dispatch:
    inputs:
      project-name:
        type: string
        required: true

env:
  PYTHON_VERSION: '3.10'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  create-repo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create repository
        env:
          GH_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        run: |
          sudo apt install gh -y
          echo "CODE is ${{ inputs.project-name }}"
          gh repo create ${{ inputs.project-name }} --public --description "ML project for ${{ inputs.project-name }} "
